<?php global $zon, $site_url; ?>
<div class="logo-container">
  <div class="logo-flex">
        <?= count(HomeFeedGames()) > 0 ? LoadFile("navbar/content") : '' ?>
  </div>
</div>
<section id="games" class="empty-thumb">
        <?php if (count(HomeFeedGames()) > 0) {
            foreach (HomeFeedGames() as $game) { ?>
            <article class="games">
              <div class="thumb">
                <a href="<?= $site_url ?>g/<?= $game['game_slug'] ?>" title="<?= $game['game_name'] ?>">
                  <div class="thumbcover"></div>
                  <div class="thumb">
                    <img width="130" height="130" alt="<?= $game['game_name'] ?>" title="<?= $game['game_name'] ?>" src="<?= $game['game_image_url'] ?>">
                    <div class="gametitle"><?= $game['game_name'] ?></div>
                  </div>
                </a>
              </div>
              <div class="new-badge">
                <img width="100%" height="100%" alt="New-Label" title="New-Label" class="new-badge" src="https://www.al3abe.online/wp-content/themes/al3abe.online/images/new.svg">
              </div>
            </article>
            <?php }
        } ?>
</section>

<div id="maincategory" class="maincategory">
            <?php foreach (getCategory() as $category) {
                $game = GameByCategoryWise($category['name'], 1)[0];
                ?>
              <a href="<?= $site_url . $category['slug'] ?>" class="mainthumb">
                <div class="thumbcategory">
                  <div class="catthumbbtn">
                    <img src="<?= $site_url ?>static/img/<?= makeSlug($category['name']) ?>.png" style="width:100%" alt="<?= $category['name'] ?>">
                    <div class="catslidetext"><?= $category['name'] ?></div>
                  </div>
                </div>
              </a>
            <?php } ?>
</div>

<div class="description bottomfooter">
  <div>
    <span>
      <a href="https://www.al3abe.online/">الرئيسية</a>
    </span>
    <span> » </span>
    <span>
      <a href="https://www.al3abe.online/">العاب تلبيس بنات</a>
    </span>
  </div>
  <div>
      <h1><?= $zon['config']['site_name'] ?></h1>
            <div class="html-content">
                <?= $zon['config']['footer_content'] ?>
            </div>
  </div>
</div>